python render_scan.py chair01
python render_scan.py chair17
python render_scan.py chair30
python render_scan.py chair26
python render_scan.py chair21
python render_scan.py chair10
python render_scan.py chair06
python render_scan.py chair15
python render_scan.py chair03
python render_scan.py chair08
python render_scan.py chair24
python render_scan.py chair32
python render_scan.py chair19
python render_scan.py chair23
python render_scan.py chair28
python render_scan.py chair04
python render_scan.py chair12
python render_scan.py chair34
python render_scan.py chair22
python render_scan.py chair18
python render_scan.py chair05
python render_scan.py chair13
python render_scan.py chair29
python render_scan.py chair14
python render_scan.py chair02
python render_scan.py chair25
python render_scan.py chair33
python render_scan.py chair09
python render_scan.py chair20
python render_scan.py chair11
python render_scan.py chair07
python render_scan.py chair00
python render_scan.py chair16
python render_scan.py chair31
python render_scan.py chair27
