python render_scan.py chair10
python render_scan.py chair59
python render_scan.py chair4
python render_scan.py chair21
python render_scan.py chair52
python render_scan.py chair37
python render_scan.py chair44
python render_scan.py chair8
python render_scan.py chair43
python render_scan.py chair55
python render_scan.py chair26
python render_scan.py chair17
python render_scan.py chair48
python render_scan.py chair6
python render_scan.py chair12
python render_scan.py chair61
python render_scan.py chair28
python render_scan.py chair35
python render_scan.py chair46
python render_scan.py chair23
python render_scan.py chair50
python render_scan.py chair19
python render_scan.py chair57
python render_scan.py chair41
python render_scan.py chair32
python render_scan.py chair1
python render_scan.py chair15
python render_scan.py chair39
python render_scan.py chair56
python render_scan.py chair25
python render_scan.py chair40
python render_scan.py chair33
python render_scan.py chair38
python render_scan.py chair29
python render_scan.py chair13
python render_scan.py chair60
python render_scan.py chair7
python render_scan.py chair47
python render_scan.py chair51
python render_scan.py chair42
python render_scan.py chair31
python render_scan.py chair54
python render_scan.py chair27
python render_scan.py chair9
python render_scan.py chair2
python render_scan.py chair49
python render_scan.py chair16
python render_scan.py chair36
python render_scan.py chair45
